steps:
   - id: build
     name: eu.gcr.io/$PROJECT_ID/gckb-example-builder
     volumes:
     - name: 'vol1'
       path: /volume
     env: 
     - 'sdsadas'
     - 'HOST_INSTANCE=test-instance'
     args: 
     - |
           echo $PROJECT_ID
   # - id: build-2
   #   name: eu.gcr.io/$PROJECT_ID/gckb-example-builder
   #   volumes:
   #   - name: 'vol1'
   #     path: /volume
   #   args: 
   #    - |
   #        cat /volume/env.sh
