FROM ubuntu:16.04
MAINTAINER "michel.laporte@essencedigital.com"
# Update the APT cache & Backup Sources list
RUN sed -i.bak 's/main$/main universe/' /etc/apt/sources.list
RUN apt-get update --fix-missing
#Install requirements
RUN apt-get install -y \
apt-utils \
curl \
wget \
locales \
software-properties-common \
ruby-full
RUN add-apt-repository -y ppa:webupd8team/java
RUN apt-get install -y oracle-java8-installer
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

#variables
ENV USER looker
ENV HOME_DIR /home/looker/looker
#ENV MEM="`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`"
#ENV JM="`expr $MEM \* 6 / 10`"
#ENV JAVAMEM="${JM}k"
#ENV METAMEM="800m"

#Add Looker and Group and Locales
RUN locale-gen en_GB en_GB.UTF-8
RUN groupadd $USER
RUN useradd -m -g $USER $USER

#switch to Looker
WORKDIR $HOME_DIR

#Ports To Expose
EXPOSE 9999
EXPOSE 19999

#Switch to $user
USER $USER

CMD exec java -XX:+UseG1GC -XX:MaxGCPauseMillis=2000 -XX:MaxMetaspaceSize=800m -Xms1228228k -Xmx1228228k -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:/tmp/gc.log -jar looker.jar start --no-daemonize