FROM ubuntu:16.04
MAINTAINER "michel.laporte@essencedigital.com"
# Update the APT cache & Backup Sources list
RUN sed -i.bak 's/main$/main universe/' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y software-properties-common

ENV USER looker
ENV HOME_DIR /home/looker/looker

#Add Looker and Group
RUN groupadd $USER
RUN useradd -m -g $USER $USER

#Navigate to looker home dir
WORKDIR $HOME_DIR

#switch to Looker
#RUN mkdir $HOME_DIR

#Download Looker Jar
ADD ./looker-latest.jar .
ADD ./looker.sh .
RUN mv looker-latest.jar looker.jar
RUN chown $USER:$USER looker.jar
RUN chown $USER:$USER looker.sh
RUN chmod +x looker.sh
RUN chown -R $USER:$USER $HOME_DIR
USER $USER
VOLUME /home/looker/looker
